version: '3.3'
services:
  backend_api:
    container_name: backend_api
    image: backend_api:latest
    restart: on-failure
    build: .
    depends_on:
      - db
    networks:
      - backend_api_network
    ports:
      - '9000:9000'
    expose:
      - '9000'

  db:
    container_name: mysql_database
    image: mysql:8.0.32
    restart: always
    networks:
      - backend_api_network
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'superuser'
      MYSQL_USER_PRIVILEGES: "db.*:ALL"
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db_api:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_db_api:


networks:
  backend_api_network:
    driver: bridge