version: '3.3'
services:
  backend_api:
    container_name: backend_api
    image: backend_api:latest
    links:
      - db
    networks:
      - backend_api_network
    ports:
      - '9000:9000'
    expose:
      - '9000'

  db:
    container_name: mysql_database
    image: mysql:8.0.32
    restart: always
    networks:
      - backend_api_network
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'qwerty'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'superuser'
      MYSQL_USER_PRIVILEGES: "db.*:ALL"
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_db_api:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_db_api:


networks:
  backend_api_network:
    driver: bridge