version: '3.3'
services:
  backend_api:
    container_name: backend_api
    image: backend_api:latest
    build: .
    # restart: always
    # environment:
    #   - DB_URL=root:superuser@(db_service)/article
    # depends_on:
    #   - database
    ports:
      - '9000:9000'


# Names our volume
volumes:
  backend_db:

networks:
  default:
    name: local-network-sharing
    external: true